name = "Ahorn"
uuid = "10a6d802-9bc0-11e8-304a-1bca7ec2ebad"
authors = ["Cruor <cruoratmc@gmail.com>", "Vexatos <Stuarzt@gmx.de>"]
version = "1.0.0"

[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
Maple = "90d5db4a-9bb6-11e8-1220-8362fcebe760"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
WinReg = "1b915085-20d7-51cf-bf83-8f477d6f5128"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
julia = "1.3"
Cairo = "1.0.0"
Gtk = "1.0.0"
